defaults:
  - hyperparams: default_hyperparams.yaml
  - trainer: default_trainer.yaml
  - model: default_model.yaml

run_name: "test_run"
wandb_env: "../wandb_api_key.env"
train_val_files: "./pq_files_train_val.txt"
test_files: "./pq_files_test.txt"
train_val_split: [0.80, 0.20]
run_validation: True
run_test: False
earlystopping_patience: 5
