# TODO: scheduling, optimization?

lr: 1e-3
hidden_dim: 64
batch_size: 32
latent_nodes: 32
#fsq_mu_levels: [5, 4, 4, 3, 3, 3, 2, 2]
fsq_mu_levels: [64, 64, 64, 64, 32, 32, 32, 16, 16, 8, 8, 4, 4]
#fsq_alpha_levels: [1024]
#fsq_alpha_levels: [8096]
fsq_alpha_levels: [65536]
window_particles: 128
#window_particles: 256
#window_particles: 1024
#num_heads: 4
#num_layers: 2
num_heads: 8
num_layers: 4
#weight_decay: 1e-4
weight_decay: 1e-3
commit_beta: 0.25
skip_quantization: True
# TODO: early stopping
# TODO: Gradient clipping
